FROM node:20

WORKDIR /app

# 使用国内镜像源
RUN npm config set registry https://registry.npmmirror.com

COPY package.json ./
RUN npm install --production

COPY dist ./dist
COPY server ./server
COPY shared ./shared

EXPOSE 3000
ENV NODE_ENV=production
ENV PORT=3000

CMD ["node", "dist/index.js"]
